apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"creationTimestamp":"2021-12-05T12:52:54Z","labels":{"app.kubernetes.io/instance":"jenkins-zh"},"name":"jenkins-client-v0.0.9","namespace":"linuxsuren-bot"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/jenkins-zh/versions","branch":"master","name":"jenkins-versions","provider":"github"},"secret":{}},"phase":"ready","repositories":[{"action":"release","address":"https://github.com/jenkins-zh/jenkins-client","branch":"main","name":"jenkins-client","provider":"github","version":"v0.0.9"}],"secret":{"name":"linuxsuren-bot","namespace":"ks-releaser-system"},"version":"v0.0.9"},"status":{}}
    releaser.devops.kubesphere.io/hash: 7d746b45c9
  creationTimestamp: "2022-01-10T13:40:48Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: jenkins-zh
  name: jenkins-client-v0.0.9
  namespace: linuxsuren-bot
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/linuxsuren-bot/releasers/jenkins-client-v0.0.9
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/jenkins-zh/versions
      branch: master
      name: jenkins-versions
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/jenkins-zh/jenkins-client
    branch: main
    name: jenkins-client
    provider: github
    version: v0.0.9
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.9
status:
  conditions:
  - conditionType: release
    message: https://github.com/jenkins-zh/jenkins-client was released
    status: success
