apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  name: jenkins-client-v0.0.6
  namespace: linuxsuren-bot
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/jenkins-zh/versions
      branch: master
      name: jenkins-versions
      provider: github
  phase: ready
  repositories:
  - action: release
    address: https://github.com/jenkins-zh/jenkins-client
    branch: main
    name: jenkins-client
    provider: github
    version: v0.0.6
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.6

